### PR TITLE
Fix my open issues (SQL datatype and requirements.txt)

### LINKED ISSUE #2: Add `Flask-Migrate` to `requirements.txt`

### LINKED ISSUE #3: Database error after trying to use (Query-invoked autoflush)
1. Use this repo to create another repo, clone it, etc.
2. Create a venv: `python3 -m venv venv`
3. Activate the venv
4. Install requirements from the requirements.txt file (which result in much newer requirements being installed): `pip install -r requirements.txt`
5. Export the env from the README.
6. Run `flask db init` and `flask db migrate` and `flask db upgrade`.
7. Run `flask run`.
8. Load the homepage.
9. Observe the following error:
```
sqlalchemy.exc.InterfaceError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.InterfaceError) Error binding parameter 3 - probably unsupported type.
[SQL: INSERT INTO role (name, description, level, permissions) VALUES (?, ?, ?, ?)]
[parameters: ('owner', 'Owner', 1000, ['view_acp', 'remove_admin'])]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
```

This is the `pip freeze` output:
```
alembic==1.8.1
Babel==2.11.0
blinker==1.5
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
dnspython==2.2.1
email-validator==1.3.0
Flask==2.2.2
Flask-BabelEx==0.9.4
Flask-Login==0.6.2
Flask-Mail==0.9.1
Flask-Migrate==4.0.0
Flask-Principal==0.4.0
Flask-Security-Too==5.0.2
Flask-SQLAlchemy==3.0.2
Flask-WTF==1.0.1
gitdb==4.0.9
GitPython==3.1.29
greenlet==2.0.1
idna==3.4
importlib-metadata==5.0.0
importlib-resources==5.10.0
itsdangerous==2.1.2
Jinja2==3.1.2
Mako==1.2.4
MarkupSafe==2.1.1
passlib==1.7.4
pytz==2022.6
requests==2.28.1
smmap==5.0.0
speaklater==1.3
SQLAlchemy==1.4.44
urllib3==1.26.12
Werkzeug==2.2.2
WTForms==3.0.1
zipp==3.10.0
```

* Using SQLite

### PR DESCRIPTION
**Pull request by DeflateAwning**
Fix #2 
Fix #3

### CODE REVIEW

**Comment by hrishikeshrt** [comment]
I am curious and haven't checked myself, is the `JSON` type requirement introduced by later version of `Flask-security-too`?

**Comment by DeflateAwning** [comment]
I'm not sure; it doesn't seem like it ever should have worked. Perhaps sqlalchemy used to implicitly convert the list-of-strings to a string to store it in the database, and did the opposite on read.

**Comment by hrishikeshrt** [comment]
I actually have a couple of projects that are still using `String(255)` and working fine.
I am on Flask 2.2.2, Flask-Security-Too 4.1.2, Flask-SQLAlchemy 2.5.1, SQLAlchemy 1.4.32. 

Will investigate this a bit more. Will also merge this soon.

**Comment by DeflateAwning** [comment]
My completely-unsubstantiated guess is that it's Flask-SQLAlchemy v2 to v3 that breaks it, though it could be Flask-Security-Too v4 to v5. 

In your working projects, what does the value of the column look like as a `String(255)` type?

**Comment by hrishikeshrt** [comment]
It is indeed a Flask-security-too 5.x change.

Please refer to https://flask-security-too.readthedocs.io/en/stable/changelog.html#version-5-0-0

> Permissions **THIS IS A BREAKING CHANGE.** The Role Model now stores permissions as a list, and requires that the underlying DB ORM map that to a supported DB type. For SQLAlchemy, this is mapped to a comma separated string (as before). For SQLAlchemy DBs the underlying Column type (UnicodeText) didn’t change so no data migration should be required. However, the ORM Column type did change and requires the following change to your model:
> 
> ```python3
> from flask_security import AsaList
> from sqlalchemy.ext.mutable import MutableList
> class Role(Base, RoleMixin):
>     ...
>     permissions = Column(MutableList.as_mutable(AsaList()), nullable=True)
>     ...
> ```

I would request you to kindly use this fix instead of `JSON` as column type.
>

**Comment by DeflateAwning** [comment]
I'll make this change and resubmit!

**Pull request closed without merging**
